### ISSUE TITLE
Instagram: Videos no longer being imported to local Media Library

### ISSUE THREAD

**Issue by beaulebens** [beaulebens/keyring-social-importers#14]
Something seems to have changed recently, and Instagram videos are no longer being downloaded to the local Media Library (or updated/replaced into the post itself).

Reported here: https://wordpress.org/support/topic/instagram-videos-5/#post-9421904

**Comment by beaulebens** [comment]
I've verified that using the last version of the importers (pull from Github), this is working.

Using the reprocessor that's bundled, you can recover previous videos.

**Comment by hernanriveraluque** [comment]
Hi @beaulebens,
What do you mean 'using last version of the importers (pull from Github)' I have installed the v1.8 fo the Keyring Social Importers and  it is not importing videos still.
Please can you explain to me what I should do?
Many thanks, appreciate the help.

**Comment by beaulebens** [comment]
Hi @hernanriveraluque -- I haven't done a new full release of the plugin, so to get the latest you'll need to download from here (GitHub) to get the very latest changes.

This link will give you a zip of the latest, which you can install directly into WordPress (remove the previous version, then just install by uploading the zip): https://github.com/beaulebens/keyring-social-importers/archive/master.zip

You might want to rename the file before using it to "keyring-social-importers" to make sure it installs into a similar-named directory as if you installed straight from the plugin repo. I'll try to get a new release done soon which will avoid needing to do any of this as well.
