### ISSUE TITLE
Respect privacy settings in source

### ISSUE THREAD

**Issue by xavierroy** [beaulebens/keyring-social-importers#15]
If a post is set to Private in the source application, it should be set to Private in WP also.

Sometimes I check-in at places but set them as private check-ins. The importer imports them but sets them as public posts, instead of private posts.

**Comment by beaulebens** [comment]
This is completely different for every service, so would need to be assessed and implemented on a case by case basis. It sounds like you're referring specifically to Foursquare/Swarm in this case, is that right?

**Comment by dshanske** [comment]
If you set geodata, do you set the geo_public flag, which is a consistent flag for location vs private posting, for example?

**Comment by beaulebens** [comment]
Yes, geodata is being set wherever possible, but it's currently always set to public (e.g. [here](https://github.com/beaulebens/keyring-social-importers/blob/master/importers/keyring-importer-foursquare.php#L299) ).

That can be changed pretty easily though. What we need is to know which of the source services support private geo data, and how it's indicated in their API responses. Also then what to do with it -- for example, setting the geo data itself as private seems like a good move, but what about the post within WordPress? Should that be Private? Password protected? Still public? Open to ideas.

I just checked an "off the grid" check-in for Swarm and it looks like that information is indicated in the API response under the `visibility` property, which is set to `private` and also under the `private` property, which is set to `1`.

**Comment by dshanske** [comment]
I develop a WordPress location plugin called Simple Location that I think @xavierroy uses.

**Comment by beaulebens** [comment]
I've addressed this in `master`, and also added a reprocessor to fix old posts.
