### ISSUE TITLE
Twitter importer no longer creating connection

### ISSUE THREAD

**Issue by davidwolfpaw** [beaulebens/keyring-social-importers#21]
I updated my Twitter account recently and yesterday went to clean up connections. I deleted the Twitter connection, which was still pulling tweets in, but listed with the old account. When I tried the test feature on the service connections page, it returned the error "This connection is NOT working correctly."

I tried to reconnect with the current app, and with a new app that I created. Each time that I've tried I've received the error "There was a problem connecting to Twitter to create an authorized connection. Please try again in a moment."

I understand that Twitter is making yet more API changes. I'm not sure if this is related. My other connections still work, and I was able to reauthenticate where needed. Some custom connections that I wrote are also still working; Twitter is the only connection that I had active that is no longer working.

**Comment by beaulebens** [comment]
I'm looking at this now, and I tried connecting using an old application configuration. I got the same error:

<img width="804" alt="Screen Shot 2019-09-07 at 3 37 16 PM" src="https://user-images.githubusercontent.com/108942/64480474-74af1e80-d185-11e9-80c6-a6912590b647.png">

When I checked the error log, I see a message about "Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings", so I went to the app configuration details on Twitter (https://developer.twitter.com/en/apps) and noticed that my callback URL was https, while my current dev URL was http. I added the http version (and had to update some other details) -- note that I had to use the full sample URL that the Twitter configuration screen in Keyring gives you (ending in `/wp-admin/tools.php`). After doing that, I was able to connect as normal, using the current version of Keyring + Importers.
