### ISSUE TITLE
Instapaper: import full content

### ISSUE THREAD

**Issue by Cliffus** [beaulebens/keyring-social-importers#24]
Hi Beau

I'm interested in using the Instapaper importer, but I'm unable to import the full content of a saved Instapaper article. I noticed the following description for the Instapaper importer:

> * NEW: Downloads the full content of the article using Instapaper's API, and stores that *in the post content*, so that you can search it later. Disable it by creating a stub plugin, or dropping this in your theme's functions.php; add_filter( 'keyring_instapaper_download_article_texts', '__return_false' );

Is this feature already available or does it need some more development?

Thanks a lot!

Kind regards
Cliff

**Comment by beaulebens** [comment]
You need a [premium Instapaper account](https://www.instapaper.com/premium) for the API to work and access the full text of an article. You also need to [get an OAuth token](https://www.instapaper.com/api/full).
