### ISSUE TITLE
Strava imports stopped working

### ISSUE THREAD

**Issue by marekhrabe** [beaulebens/keyring-social-importers#32]
My activities have stopped syncing. When I run the importer manually, it shows an error:

```
Strava Importer
We got an unknown error back from Strava. This is what they said.

{"message":"Authorization Error","errors":[
  {"resource":"AccessToken","field":"activity:read_permission","code":"missing"}
]}
```

It is be possible Strava has changed scopes required to read content from profiles. I might look into this in a few weeks if nobody else beats me to it

**Comment by mdrovdahl** [comment]
Indeed, see https://github.com/beaulebens/keyring/issues/43

**Comment by beaulebens** [comment]
Please check out the thread that @mdrovdahl linked above, and see if the change in https://github.com/beaulebens/keyring/commit/31d71527a05b1c575876f82d664b39bc5a3b66e9 fixes this for you!

**Comment by beaulebens** [comment]
Actually -- for this to work on importing activities, you need to change the `scope` to `read,activity:read_all`. I'll probably just go ahead and do that in the base service, but in the meantime you can also do it via filter on `keyring_strava_scope`.

**Comment by beaulebens** [comment]
I went ahead and modified the scope requested in https://github.com/beaulebens/keyring/commit/4a0f839c72c866502c9a0a121c32e2eaaf8abc8f so this should work for importing activities again now.

**Comment by marekhrabe** [comment]
I have tested with the `master` branch of keyring and things are back to normal! Except better because it now seems to support private activities? That's awesome

**Comment by beaulebens** [comment]
Oh yeah, the new scope I'm requesting also grants access to those private activities! I'll update this to default those to private posts, per #33. Going to close this one now since it sounds like we're good to go!
