### ISSUE TITLE
Instagram not working

### ISSUE THREAD

**Issue by Null-Mind** [beaulebens/keyring-social-importers#38]
I deleted and re-uploaded keyring and the social importers form githug

when I try to connect to instagram, I get this dump on the page

{"error_type": "OAuthException", "code": 400, "error_message": "Invalid scope field(s): basic"}

Any ideas ?

**Comment by beaulebens** [comment]
Unfortunately I believe Instagram is going to require a complete re-thinking now that they've changed all of their API access. Closing for now.
