### ISSUE TITLE
Twitter: t.co links are not converted

### ISSUE THREAD

**Issue by beaulebens** [beaulebens/keyring-social-importers#7]
Twitter converts links to t.co shortlinks when you create a Tweet. The importer should reverse that back to the original link when creating a local post (available via `entities` property in the import data, so can also add a reprocessor to got back and fix old posts).

Originally [reported here](https://wordpress.org/support/topic/twitter-imports-rts-though-option-isnt-checked/).

**Comment by ChrisHardie** [comment]
Proposed fix and reprocessor in https://github.com/beaulebens/keyring-social-importers/pull/11/commits/584178141cc11ff4af59abff43fa13cdc128a946. Tested against latest WP and ~200 tweets that include regular links, media, retweets, etc.

**Comment by beaulebens** [comment]
Fixed in a992093af71e7105b63cffefa3b6029c2c1951ba
