### ISSUE TITLE
Twitter: Importing RTs even with the option unchecked

### ISSUE THREAD

**Issue by beaulebens** [beaulebens/keyring-social-importers#8]
The Twitter importer seems to be importing retweets, even if the option is unchecked.

[Originally reported here](https://wordpress.org/support/topic/twitter-imports-rts-though-option-isnt-checked/).

**Comment by glueckpress** [comment]
I fixed the RT issue with a hack on my site by inserting the following check [here](https://github.com/beaulebens/keyring-social-importers/blob/master/importers/keyring-importer-twitter.php#L182):

```php
// Double-check for retweets, which shouldn't be included at all if we chose to skip them
if ( false == $this->get_option( 'include_rts', true ) && ! empty( $post->retweeted_status ) ) {
	continue;
}
```

Not sure if this is ideal, but it seems to fix the issue for me.

**Comment by beaulebens** [comment]
@glueckpress your approach will work, but I believe the fix I just committed to `master` handles it further up. It turns out you have to explicitly set `include_rts` to `false` in the request (not just exclude it) to make Twitter leave out retweets. Check it out, and please let me know if that works for you!

**Comment by glueckpress** [comment]
Awesome, installed the fixed master, works perfectly! Thanks!

**Comment by beaulebens** [comment]
Awesome, it'll be part of the next release. Thanks for confirming.
